version: '3.8'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employee_db
    ports:
      - '3306:3306'
  backend:
    build: .
    ports:
      - '4000:4000'
    depends_on:
      - db
